### ISSUE TITLE
com.mongodb.MongoSocketReadException: Exception receiving message

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1014]
过一段时间不访问，会出现这个异常，通过turms-admin登录的时候第一次不行，点下登录，又恢复了。
是我装的mongodb的问题，还是什么问题咯
 2022-09-19 16:23:15.003  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:23:30.000  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:23:45.000  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:24:00.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:24:15.006  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:24:30.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:24:45.000  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:25:00.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:25:15.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:25:30.005  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:25:45.002  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:26:00.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:26:03.070  INFO S iottjpum                     mongo-event-loop-8-1               org.mongodb.driver.cluster : Cluster description not yet available. Waiting for 30000 ms before timing out

 2022-09-19 16:26:06.063  INFO S iottjpum                     turms-health-checker-3-1               org.mongodb.driver.cluster : No server chosen by com.mongodb.reactivestreams.client.internal.ClientSessionHelper$$Lambda$1229/0x00000008012d7d48@74dc4d0e from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=39.108.66.206:32654, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}]}. Waiting for 30000 ms before timing out

 2022-09-19 16:26:13.066  INFO S iottjpum                     turms-node-discovery-heartbeat-refresher               org.mongodb.driver.cluster : No server chosen by com.mongodb.reactivestreams.client.internal.ClientSessionHelper$$Lambda$1229/0x00000008012d7d48@5ef8f58e from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=39.108.66.206:32654, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}]}. Waiting for 30000 ms before timing out

 2022-09-19 16:26:13.066  INFO S iottjpum                     turms-node-discovery-heartbeat-refresher               org.mongodb.driver.cluster : No server chosen by com.mongodb.reactivestreams.client.internal.ClientSessionHelper$$Lambda$1229/0x00000008012d7d48@12239ce4 from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=39.108.66.206:32654, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}]}. Waiting for 30000 ms before timing out

 2022-09-19 16:26:13.066 ERROR S iottjpum                     parallel-1   i.t.s.c.i.c.s.d.LocalNodeStatusManager : Failed to send heartbeat request

 java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'source(MonoWhen)' (and no fallback has been configured)

 	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)

 	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)

 	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)

 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)

 	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)

 	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)

 	at im.turms.server.common.infra.tracing.TracingContext.lambda$static$0(TracingContext.java:63)

 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)

 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)

 	at java.util.concurrent.FutureTask.run(unknown)

 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(unknown)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(unknown)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(unknown)

 	at java.lang.Thread.run(unknown)

 

 2022-09-19 16:26:15.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:26:23.066  INFO S iottjpum                     turms-node-discovery-heartbeat-refresher               org.mongodb.driver.cluster : No server chosen by com.mongodb.reactivestreams.client.internal.ClientSessionHelper$$Lambda$1229/0x00000008012d7d48@40309a22 from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=39.108.66.206:32654, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}]}. Waiting for 30000 ms before timing out

 2022-09-19 16:26:23.066  INFO S iottjpum                     turms-node-discovery-heartbeat-refresher               org.mongodb.driver.cluster : No server chosen by com.mongodb.reactivestreams.client.internal.ClientSessionHelper$$Lambda$1229/0x00000008012d7d48@1af9b16e from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=39.108.66.206:32654, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}]}. Waiting for 30000 ms before timing out

 2022-09-19 16:26:23.066 ERROR S iottjpum                     parallel-1   i.t.s.c.i.c.s.d.LocalNodeStatusManager : Failed to send heartbeat request

 java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'source(MonoWhen)' (and no fallback has been configured)

 	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)

 	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)

 	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)

 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)

 	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)

 	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)

 	at im.turms.server.common.infra.tracing.TracingContext.lambda$static$0(TracingContext.java:63)

 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)

 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)

 	at java.util.concurrent.FutureTask.run(unknown)

 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(unknown)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(unknown)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(unknown)

 	at java.lang.Thread.run(unknown)

 

 2022-09-19 16:26:30.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:26:33.066 ERROR S iottjpum                     parallel-1   i.t.s.c.i.c.s.d.LocalNodeStatusManager : Failed to send heartbeat request

 java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'source(MonoWhen)' (and no fallback has been configured)

 	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)

 	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)

 	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)

 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)

 	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)

 	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)

 	at im.turms.server.common.infra.tracing.TracingContext.lambda$static$0(TracingContext.java:63)

 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)

 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)

 	at java.util.concurrent.FutureTask.run(unknown)

 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(unknown)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(unknown)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(unknown)

 	at java.lang.Thread.run(unknown)

 

 2022-09-19 16:26:33.067  INFO S iottjpum                     turms-node-discovery-heartbeat-refresher               org.mongodb.driver.cluster : No server chosen by com.mongodb.reactivestreams.client.internal.ClientSessionHelper$$Lambda$1229/0x00000008012d7d48@334633a from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=39.108.66.206:32654, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}]}. Waiting for 30000 ms before timing out

 2022-09-19 16:26:33.067  INFO S iottjpum                     turms-node-discovery-heartbeat-refresher               org.mongodb.driver.cluster : No server chosen by com.mongodb.reactivestreams.client.internal.ClientSessionHelper$$Lambda$1229/0x00000008012d7d48@d7e0b04 from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=39.108.66.206:32654, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Exception receiving message}, caused by {java.net.SocketException: Connection reset}}]}. Waiting for 30000 ms before timing out

 2022-09-19 16:26:33.078  INFO S iottjpum                     cluster-ClusterId{value='6326df1bcddb994179e1aa15', description='null'}-39.108.66.206:32654            org.mongodb.driver.connection : Opened connection [connectionId{localValue:151, serverValue:53392}] to 39.108.66.206:32654

 2022-09-19 16:26:33.078  INFO S iottjpum                     cluster-ClusterId{value='6326df1bcddb994179e1aa15', description='null'}-39.108.66.206:32654               org.mongodb.driver.cluster : Monitor thread successfully connected to server with description ServerDescription{address=39.108.66.206:32654, type=SHARD_ROUTER, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=3627175}

 2022-09-19 16:26:33.126  INFO S iottjpum                     mongo-event-loop-8-1            org.mongodb.driver.connection : Opened connection [connectionId{localValue:152, serverValue:53393}] to 39.108.66.206:32654

 2022-09-19 16:26:33.129  INFO S iottjpum                     mongo-event-loop-8-1            org.mongodb.driver.connection : Opened connection [connectionId{localValue:153, serverValue:53394}] to 39.108.66.206:32654

 2022-09-19 16:26:33.153  INFO S iottjpum                     mongo-event-loop-8-1            org.mongodb.driver.connection : Opened connection [connectionId{localValue:154, serverValue:53395}] to 39.108.66.206:32654

 2022-09-19 16:26:45.000  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:27:00.001  INFO S iottjpum                     turms-task-manager            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:27:03.111  INFO S iottjpum                     mongo-event-loop-8-1            org.mongodb.driver.connection : Opened connection [connectionId{localValue:155, serverValue:53404}] to 39.108.66.206:32654

 2022-09-19 16:27:06.681  INFO S iottjpum 5100472166282051177 turms-admin-http-worker-21-1 : |172.18.8.202|f2a2bd43-2|2022-09-19 16:27:06.681|checkAccountAndPassword|{}|TRUE|0|

 2022-09-19 16:27:06.749  INFO S iottjpum                     mongo-event-loop-1-1               org.mongodb.driver.cluster : Cluster description not yet available. Waiting for 30000 ms before timing out

 2022-09-19 16:27:15.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:27:30.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:27:36.750  INFO S iottjpum 5874358781667344238 mongo-event-loop-1-1 : turms|172.18.8.202|f2a2bd43-4|2022-09-19 16:27:06.745|queryAdmins|{withPassword=false, accounts=[turms]}|FALSE|30005|com.mongodb.MongoSocketReadException: Exception receiving message

 2022-09-19 16:27:36.754 ERROR S iottjpum 5874358781667344238 mongo-event-loop-1-1      i.t.s.c.a.a.w.HttpRequestDispatcher : Caught an error while handling the HTTP request: GET{uri=/admins?accounts=turms, connection=SimpleConnection{channel=[id: 0xf2a2bd43, L:/10.233.70.51:8510 - R:/172.18.8.202:50792]}}

 com.mongodb.MongoSocketReadException: Exception receiving message

 	at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:702)

 	at com.mongodb.internal.connection.InternalStreamConnection.access$800(InternalStreamConnection.java:86)

 	at com.mongodb.internal.connection.InternalStreamConnection$5.failed(InternalStreamConnection.java:651)

 	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:316)

 	at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:347)

 	at com.mongodb.connection.netty.NettyStream.access$1100(NettyStream.java:105)

 	at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.exceptionCaught(NettyStream.java:429)

 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)

 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)

 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)

 	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)

 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)

 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)

 	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)

 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125)

 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177)

 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)

 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)

 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)

 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)

 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)

 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

 	at java.lang.Thread.run(unknown)

 

 caused by: java.net.SocketException: Connection reset

 	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(unknown)

 	at sun.nio.ch.SocketChannelImpl.read(unknown)

 	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)

 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)

 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)

 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)

 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)

 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)

 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)

 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)

 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)

 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

 	at java.lang.Thread.run(unknown)

 

 2022-09-19 16:27:36.762  INFO S iottjpum                     cluster-ClusterId{value='6326df19cddb994179e1aa14', description='null'}-39.108.66.206:32654            org.mongodb.driver.connection : Opened connection [connectionId{localValue:156, serverValue:53413}] to 39.108.66.206:32654

 2022-09-19 16:27:36.762  INFO S iottjpum                     cluster-ClusterId{value='6326df19cddb994179e1aa14', description='null'}-39.108.66.206:32654               org.mongodb.driver.cluster : Monitor thread successfully connected to server with description ServerDescription{address=39.108.66.206:32654, type=SHARD_ROUTER, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=3637770}

 2022-09-19 16:27:45.000  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:28:00.025  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:28:15.001  INFO S iottjpum                     turms-task-manager            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:28:30.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:28:45.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:29:00.002  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:29:03.925  INFO S iottjpum 8000088183328692924 turms-admin-http-worker-21-1 : |172.18.8.202|f2a2bd43-6|2022-09-19 16:29:03.924|checkAccountAndPassword|{}|TRUE|1|

 2022-09-19 16:29:04.009  INFO S iottjpum                     mongo-event-loop-1-1            org.mongodb.driver.connection : Opened connection [connectionId{localValue:157, serverValue:53441}] to 39.108.66.206:32654

 2022-09-19 16:29:04.016  INFO S iottjpum  384534416684258093 mongo-event-loop-1-1 : turms|172.18.8.202|f2a2bd43-8|2022-09-19 16:29:03.983|queryAdmins|{withPassword=false, accounts=[turms]}|TRUE|32|

 2022-09-19 16:29:04.102  INFO S iottjpum                     mongo-event-loop-1-1            org.mongodb.driver.connection : Opened connection [connectionId{localValue:158, serverValue:53442}] to 39.108.66.206:32654

 2022-09-19 16:29:04.109  INFO S iottjpum 7452247560916158759 mongo-event-loop-1-1 : turms|172.18.8.202|f2a2bd43-10|2022-09-19 16:29:04.076|queryUsers|{size=20, page=0}|TRUE|32|

 2022-09-19 16:29:15.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:29:30.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:29:45.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:30:00.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:30:15.000  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:30:30.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:30:45.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

 2022-09-19 16:31:00.001  INFO S iottjpum                     turms-node-connection-server-worker-5-1            i.t.s.d.o.s.StatisticsService : The current online users number is: 0

**Comment by itmagus** [comment]
看下本地的连接参数，是否要设置下maxConnectionIdleTime的参数，是0
org.mongodb.driver.client : MongoClient with metadata {"driver": {"name": "mongo-java-driver|reactive-streams", "version": "4.6.0"}, "os": {"type": "Windows", "name": "Windows 10", "architecture": "amd64", "version": "10.0"}, "platform": "Java/Oracle Corporation/17.0.3.1+2-LTS-6"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=null, streamFactoryFactory=NettyStreamFactoryFactory{eventLoopGroup=io.netty.channel.nio.NioEventLoopGroup@6801b414, socketChannelClass=class io.netty.channel.socket.nio.NioSocketChannel, allocator=PooledByteBufAllocator(directByDefault: true), sslContext=null}, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DocumentCodecProvider{}, MapCodecProvider{}, IterableCodecProvider{}, GeoJsonCodecProvider{}, Jsr310CodecProvider{}, BsonCodecProvider{}]}, ProvidersCodecRegistry{codecProviders=[im.turms.server.common.storage.mongo.codec.MongoCodecProvider@177c41d7]}]}, clusterSettings={hosts=[localhost:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[im.turms.server.common.storage.mongo.MongoContext$1@4f327096]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=UNSPECIFIED, serverApi=null, autoEncryptionSettings=null, contextProvider=null}

**Comment by JamesChenX** [comment]
As the logs hint, the mongo client failed to find an available server to handle requests since the connection has been reset.

1. `maxConnectionIdleTime` should not fix this problem because it is 0 by default, meaning these connections won't become idle so they should not closed by the mongo client because of idleness.
2. You can use `minpoolsize` (e.g. `mongodb://127.0.0.1:27017/turms-dev?minpoolsize=5`) to ensure the mongo client keeps these connections in the pool so that you can ensure there are connections of the specific number available after startup.
3. If you want to know why the connection is closed, you can set breakpoints at these two methods to know the reason: `com.mongodb.internal.connection.DefaultConnectionPool.UsageTrackingInternalConnectionItemFactory#getReasonStringForClosing` and `com.mongodb.internal.connection.DefaultConnectionPool.UsageTrackingInternalConnectionItemFactory#getReasonForClosing`

**Comment by itmagus** [comment]
配置了minpoolsize，是一样的，不过这里应该只是个连接池的配置的问题，问题不大，保持连接的有效性就行

**Comment by itmagus** [comment]
通过调整连接池的参数，已经解决
