### ISSUE TITLE
k8s plugin not load

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1076]
我还测试了另一种方式
把插件放到plugins目录下
在本地启动正常
当我把插件打包到镜像中后
然后部署到k8s中，好像没有去加载插件，看不到任何加载插件的日志

**Comment by itmagus** [comment]
我想我知道问题了
在docker中加载的路径是/opt/turms/turms-service/plugins，而不是/opt/turms/plugins

**Comment by itmagus** [comment]
不幸运的是依然报错
caused by: java.lang.ClassNotFoundException: im.turms.server.common.infra.plugin.TurmsPlugin

 	at java.net.URLClassLoader.findClass(unknown)

 	at java.lang.ClassLoader.loadClass(unknown)

 	at java.lang.ClassLoader.loadClass(unknown)

 	at im.turms.server.common.infra.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43)

 	at java.lang.ClassLoader.defineClass1(native)

 	at java.lang.ClassLoader.defineClass(unknown)

 	at java.security.SecureClassLoader.defineClass(unknown)

 	at java.net.URLClassLoader.defineClass(unknown)

 	at java.net.URLClassLoader$1.run(unknown)

 	at java.net.URLClassLoader$1.run(unknown)

 	at java.security.AccessController.doPrivileged(unknown)

 	at java.net.URLClassLoader.findClass(unknown)

 	at java.lang.ClassLoader.loadClass(unknown)

 	at java.lang.ClassLoader.loadClass(unknown)

 	at im.turms.server.common.infra.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43)

 	at im.turms.server.common.infra.plugin.JavaPluginFactory.create(JavaPluginFactory.java:41)

 	at im.turms.server.common.infra.plugin.PluginManager.loadJavaPlugins(PluginManager.java:225)

 	at im.turms.server.common.infra.plugin.PluginManager.<init>(PluginManager.java:110)

 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(native)

 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(unknown)

 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(unknown)

 	at java.lang.reflect.Constructor.newInstanceWithCaller(unknown)

 	at java.lang.reflect.Constructor.newInstance(unknown)

 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)

 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)

 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)

 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)

 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)

 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)

 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)

 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)

 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)

 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)

 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)

 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)

 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)

 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)

 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)

 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)

 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)

 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)

 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)

 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)

 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)

 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)

 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)

 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)

 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)

 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)

 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)

 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)

 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)

 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)

 	at im.turms.server.common.BaseTurmsApplication.bootstrap(BaseTurmsApplication.java:51)

 	at im.turms.service.TurmsServiceApplication.main(TurmsServiceApplication.java:33)

 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(native)

 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(unknown)

 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(unknown)

 	at java.lang.reflect.Method.invoke(unknown)

 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)

 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)

 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)

 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

**Comment by itmagus** [comment]
![image](https://user-images.githubusercontent.com/8073980/201325282-9d62c22c-a109-4db8-b0ff-d02c6e7cfaf6.png)
@JamesChenX
修改后正常启动，我只能修改我本地的代码，你看下，是不是这个问题导致的哈，仅供参考

**Comment by JamesChenX** [comment]
@itmagus Fixed. Thanks for your help!
