### ISSUE TITLE
hearbeat_service ResponseException (null:301:null:null)

### ISSUE THREAD

**Issue by shengbiliPaul** [turms-im/turms#1090]
模拟器上，在对话页面待着，说明都没有做，过一段时间就会抛出异常。在hearbeat_service.dart的55行。请问这是什么引起的呢？
`[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: null:301:null:null
#0      HeartbeatService.send
package:turms_client_dart/…/service/heartbeat_service.dart:55
#1      HeartbeatService.start.<anonymous closure>
package:turms_client_dart/…/service/heartbeat_service.dart:44
#2      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#3      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)`

**Comment by shengbiliPaul** [comment]
`
  late TurmsClient _client;
  @override
  void initState() {
    super.initState();
    final client = TurmsClient(host: '192.xxxxx.53', port: 11510);
    _client = client;

    _client.messageService.addMessageListener((message, _) {
      print(
          'onMessage: Receive a message from other users or server: $message');
    });
    client.userService.login(Int64(1), password: '123');
  }

  @override
  void dispose() {
    super.dispose();
    _client.userService.logout();
    _client.close();
  }

   //消息发送
  void passTextAction() async {
    try {
      final msgId = (await _client.messageService.sendMessage(
              false, Int64(2)),
              text: 'dddd', burnAfter: 30))
          .data;
      print('message $msgId has been sent');
     
    } catch (error) {
    }
  }`

**Comment by JamesChenX** [comment]
## Background
As the status code 301 indicates, it means `client session has been closed` when sending client heartbeat requests.
You may get the exception periodically because turms client doesn't detect a socket close event, and it doesn't stop the timer for sending heartbeat requests. (In other words, if turms client detects a socket close event,  it will close the timer, and the exception will only occur once at most)

## Cause
So the direct cause is: the client session has been closed by your client operating system or turms server, but the root cause can only be inspected by logging or debugging.

And you can confirm it by listening to the close notification, including the information about why the client is closed, sent by turms-gateway if the client session is closed by turms-gateway actively:
```dart
// before calling `client.userService.login(...)`
client.userService.addOnOfflineListener((info) => print(
    'onOffline: ${info.closeStatus}:${info.businessStatus}:${info.reason}:${info.cause}\n${info.stackTrace}'));
```
With the information, we can do further research.
