### ISSUE TITLE
this.mongoClient" is null

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1128]
更新后，出现下面的错误
参数设置turms.gateway.session.identity-access-management.enabled=false
java.lang.NullPointerException: Cannot invoke "im.turms.server.common.storage.mongo.TurmsMongoClient.exists(java.lang.Class, im.turms.server.common.storage.mongo.operation.option.Filter)" because "this.mongoClient" is null
	at im.turms.gateway.domain.session.repository.UserRepository.isActiveAndNotDeleted(UserRepository.java:60)
	at im.turms.gateway.domain.session.service.UserService.isActiveAndNotDeleted(UserService.java:65)
	at im.turms.gateway.domain.session.service.SessionIdentityAccessManager.verifyAndGrantUsingPassword(SessionIdentityAccessManager.java:302)
	at im.turms.gateway.domain.session.service.SessionIdentityAccessManager.lambda$verifyAndGrant$1(SessionIdentityAccessManager.java:212)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4510)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4411)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4347)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4319)
	at im.turms.gateway.access.client.common.UserSessionAssembler.lambda$respondToRequests$9(UserSessionAssembler.java:131)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:377)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at reactor.netty.channel.AbstractChannelMetricsHandler.channelRead(AbstractChannelMetricsHandler.java:126)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)

**Comment by itmagus** [comment]
需要与turms.gateway.session.identity-access-management.type配合使用

**Comment by JamesChenX** [comment]
Thanks for reporting. I have pushed a commit to refuse and log the illegal operation that trying to enable the disabled password-based identity and access management.
