### ISSUE TITLE
【bug】IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by Firefly822** [turms-im/turms#1203]
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at jdk.internal.util.Preconditions.outOfBounds(unknown)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(unknown)
	at jdk.internal.util.Preconditions.checkIndex(unknown)
	at java.util.Objects.checkIndex(unknown)
	at java.util.ArrayList.get(unknown)
	at im.turms.server.common.infra.cluster.service.rpc.RpcService.requestResponse(RpcService.java:280)
	at im.turms.gateway.domain.servicerequest.service.ServiceRequestService.handleServiceRequest(ServiceRequestService.java:64)
	at im.turms.gateway.access.client.common.ClientRequestDispatcher.handleServiceRequest(ClientRequestDispatcher.java:339)
	at im.turms.gateway.access.client.common.ClientRequestDispatcher.handleServiceRequest(ClientRequestDispatcher.java:269)
	at im.turms.gateway.access.client.common.ClientRequestDispatcher.handleRequest(ClientRequestDispatcher.java:163)
	at im.turms.gateway.access.client.common.UserSessionAssembler.lambda$respondToRequests$9(UserSessionAssembler.java:125)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:379)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at reactor.netty.channel.AbstractChannelMetricsHandler.channelRead(AbstractChannelMetricsHandler.java:126)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(unknown)

 int index = (int) System.currentTimeMillis() % size;
should be 
        int index = (int) (System.currentTimeMillis() % size);

**Comment by JamesChenX** [comment]
Thanks for reporting!
Would you like to submit a PR to fix it? I will merge it quickly.

**Comment by Firefly822** [comment]
#1208
