### ISSUE TITLE
turms-turms-service "Failed to listen to the connection to the member"

### ISSUE THREAD

**Issue by kissingtiger** [turms-im/turms#1204]
2023-04-24 07:10:54.000  WARN S ndsqupjd                     turms-node-connection-server-worker-5-8        i.t.s.c.i.c.s.c.ConnectionService : [Server] The connection to an unknown member has been closed unexpectedly
2023-04-24 07:10:54.000  INFO S ndsqupjd                     turms-node-connection-server-worker-5-8        i.t.s.c.i.c.s.c.ConnectionService : [Server] Stop to connect the member because the local node is server
2023-04-24 07:10:55.688  INFO S ndsqupjd                     turms-node-connection-server-worker-5-1        i.t.s.c.i.c.s.c.ConnectionService : [Server] Connected to the member
2023-04-24 07:10:55.688 ERROR S ndsqupjd                     turms-node-connection-server-worker-5-1        i.t.s.c.i.c.s.c.ConnectionService : [Server] Failed to listen to the connection to the member
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(unknown)
	at sun.nio.ch.SocketChannelImpl.read(unknown)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:821)
	at io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:636)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(unknown)

**Comment by JamesChenX** [comment]
From your logs, the behavior is fine because Turms nodes will retry to connect to each other if the registration information of the peer isn't removed from MongoDB.
Note: Node registration information will be removed if the peer doesn't send `keepalive/heartbeat` request in time.
