### ISSUE TITLE
how to start minio with quickstart docker command

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1244]
When I uncomment this config
<img width="1382" alt="image" src="https://github.com/turms-im/turms/assets/54241621/b7572f56-440e-4c50-bd48-81fdf15fbe89">

and  start with ` docker compose -f docker-compose.standalone.yml up --force-recreate`

<img width="1087" alt="image" src="https://github.com/turms-im/turms/assets/54241621/242841c7-aed9-4b20-a39e-c8c08fb85243">

container "turms-service" always exit ,can not start success

**Comment by weishirongzhen** [comment]
I found some log may related:



```
suppressed: java.lang.RuntimeException: Caught errors while starting extensions of the plugin: im.turms.plugin.minio.MinioStoragePlugin
		at im.turms.server.common.infra.exception.ThrowableUtil.delayError(ThrowableUtil.java:101)
		at im.turms.server.common.infra.plugin.Plugin.start(Plugin.java:66)
		at im.turms.server.common.infra.exception.ThrowableUtil.delayError(ThrowableUtil.java:92)
		at im.turms.server.common.infra.plugin.PluginManager.startPlugins(PluginManager.java:549)
		at im.turms.server.common.infra.plugin.PluginManager.startPlugins(PluginManager.java:536)
		at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:162)
		at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:82)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
		at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
		at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:437)
		at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
		at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:961)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:611)
		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
		at im.turms.server.common.BaseTurmsApplication.bootstrap(BaseTurmsApplication.java:54)
		at im.turms.service.TurmsServiceApplication.main(TurmsServiceApplication.java:34)
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(native)
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(unknown)
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(unknown)
		at java.lang.reflect.Method.invoke(unknown)
		at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
		at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
		at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
		at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

		suppressed: java.lang.RuntimeException: Caught an error while starting the extension: im.turms.plugin.minio.MinioStorageServiceProvider
			at im.turms.server.common.infra.plugin.Plugin.lambda$start$0(Plugin.java:61)
			at im.turms.server.common.infra.exception.ThrowableUtil.delayError(ThrowableUtil.java:92)
			at im.turms.server.common.infra.plugin.Plugin.start(Plugin.java:66)
			at im.turms.server.common.infra.exception.ThrowableUtil.delayError(ThrowableUtil.java:92)
			at im.turms.server.common.infra.plugin.PluginManager.startPlugins(PluginManager.java:549)
			at im.turms.server.common.infra.plugin.PluginManager.startPlugins(PluginManager.java:536)
			at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:162)
			at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:82)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
			at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:437)
			at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
			at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:961)
			at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:611)
			at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
			at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
			at im.turms.server.common.BaseTurmsApplication.bootstrap(BaseTurmsApplication.java:54)
			at im.turms.service.TurmsServiceApplication.main(TurmsServiceApplication.java:34)
			at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(native)
			at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(unknown)
			at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(unknown)
			at java.lang.reflect.Method.invoke(unknown)
			at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
			at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
			at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
			at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

		caused by: java.lang.IllegalStateException: Timeout on blocking read for 60000000000 NANOSECONDS
			at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
			at reactor.core.publisher.Mono.block(Mono.java:1734)
			at im.turms.plugin.minio.MinioStorageServiceProvider.setUp(MinioStorageServiceProvider.java:194)
			at im.turms.plugin.minio.MinioStorageServiceProvider.onStarted(MinioStorageServiceProvider.java:160)
			at im.turms.server.common.infra.plugin.TurmsExtension.start(TurmsExtension.java:100)
			at im.turms.server.common.infra.plugin.Plugin.lambda$start$0(Plugin.java:56)
			at im.turms.server.common.infra.exception.ThrowableUtil.delayError(ThrowableUtil.java:92)
			at im.turms.server.common.infra.plugin.Plugin.start(Plugin.java:66)
			at im.turms.server.common.infra.exception.ThrowableUtil.delayError(ThrowableUtil.java:92)
			at im.turms.server.common.infra.plugin.PluginManager.startPlugins(PluginManager.java:549)
			at im.turms.server.common.infra.plugin.PluginManager.startPlugins(PluginManager.java:536)
			at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:162)
			at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:82)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
			at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
			at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:437)
			at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
			at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:961)
			at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:611)
			at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
			at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
			at im.turms.server.common.BaseTurmsApplication.bootstrap(BaseTurmsApplication.java:54)
			at im.turms.service.TurmsServiceApplication.main(TurmsServiceApplication.java:34)
			at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(native)
			at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(unknown)
			at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(unknown)
			at java.lang.reflect.Method.invoke(unknown)
			at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
			at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
			at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
			at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

**Comment by JamesChenX** [comment]
This may happen if the MongoDB server for storage is not running.

And If you use `docker-compose.standalone.yml` to run, you can add `-Dturms-plugin.minio.mongo.uri=mongodb://localhost:27017/turms` (point to your MongoDB server) in `TURMS_SERVICE_JVM_OPTS` env var to specify the MongoDB server used for storage, and try to run again.

**Comment by weishirongzhen** [comment]
if config` -Dturms-plugin.minio.mongo.uri=mongodb://localhost:27017/turms` there will be mongo db connect error, and I change to  `-Dturms-plugin.minio.mongo.uri=mongodb://mongodb-router:27017/turms-standalone?authSource=admin`
error gone, but minio still can not connect, I'm sure mino localhost/127.0.0.1:9000 is connectable, and 
added access key and access secret to default "minioadmin"
<img width="885" alt="image" src="https://github.com/turms-im/turms/assets/54241621/831a7981-3af4-48b4-a70a-16fb0b003f2b">


Full error log:
[turms-service_20230618_0.log](https://github.com/turms-im/turms/files/11780616/turms-service_20230618_0.log)

**Comment by JamesChenX** [comment]
As the logs print: `Failed to connect to localhost/127.0.0.1:9000`, it usually happens if you run the minio server and turms-service in different network environments, so you can just configure `turms-plugin.minio.endpoint` to your minio server address (e.g. `http://minio:9000`), and it should work.

btw you need to read the logs so that you can fix the basic problems yourselves.

**Comment by weishirongzhen** [comment]
Thanks a lot, problem solved, maybe it's cause by minio that i also run in docker, 127.0.0.1 point to docker env, not my machine localhost, I changed 127.0.0.1:9000 to machine router ip works.
