### ISSUE TITLE
MapCodecV2 cannot be cast to class 

### ISSUE THREAD

**Issue by zy2203** [turms-im/turms#1252]
update User Permission Group has an error.

java.lang.ClassCastException: class org.bson.codecs.MapCodecV2 cannot be cast to class im.turms.server.common.storage.mongo.codec.EntityCodec (org.bson.codecs.MapCodecV2 and im.turms.server.common.storage.mongo.codec.EntityCodec are in unnamed module of loader 'app')
	at im.turms.server.common.storage.mongo.codec.BsonValueEncoder.encodeSingleValue(BsonValueEncoder.java:126)
	at im.turms.server.common.storage.mongo.codec.BsonValueEncoder.encodeValue(BsonValueEncoder.java:72)
	at im.turms.server.common.storage.mongo.operation.option.Update.appendSet(Update.java:96)
	at im.turms.server.common.storage.mongo.operation.option.Update.setIfNotNull(Update.java:63)

![图片](https://github.com/turms-im/turms/assets/54758962/d371fb94-70a0-4311-a8da-f207e325171d)

**Comment by zy2203** [comment]
at im.turms.service.domain.user.repository.UserPermissionGroupRepository.updateUserPermissionGroups(UserPermissionGroupRepository.java:61)

groupTypeIdToLimit cannot encode to BsonValue

**Comment by JamesChenX** [comment]
Thanks for reporting.
The bug has been fixed, and you can pull the latest code or the docker images to have a try.
