### ISSUE TITLE
Can not login with multi-device

### ISSUE THREAD

**Issue by zy2203** [turms-im/turms#1255]
The config is default `turms.gateway.simultaneous-login.strategy=ALLOW_ONE_DEVICE_OF_EACH_DEVICE_TYPE_ONLINE`.

In example.dart use `DeviceType.ANDROID` login successful.
```
await client.userService.login(Int64(1), password: '123', deviceType: DeviceType.ANDROID);
```

then in example_user.dart use `DeviceType.DESKTOP` or other DeviceType login, has Exception.
```
await client.userService.login(Int64(1), password: '123', deviceType: DeviceType.DESKTOP);
```

```
java.lang.NullPointerException: Cannot invoke "im.turms.server.common.domain.session.bo.UserDeviceSessionInfo.getNodeId()" because "sessionInfo" is null
	at im.turms.gateway.domain.session.service.SessionService.lambda$tryRegisterOnlineUser$10(SessionService.java:749)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
	at reactor.core.publisher.MonoStreamCollector$StreamCollectorSubscriber.onComplete(MonoStreamCollector.java:159)
```

**Comment by JamesChenX** [comment]
Thanks for reporting.
The bug has been fixed in https://github.com/turms-im/turms/commit/606287ea2f4231952503f78ae5d96d6e081f4497, and you can pull the latest code or docker images to have a try.
