### ISSUE TITLE
[Client] Failed to connect to member: {id=thvqpcoc, host=turms, port=7510}

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1274]
after update to newest code and docker image:
when start docker always connect error

log:
```
2023-07-23 07:28:51.662  INFO G ejtkwaus                     main im.turms.gateway.TurmsGatewayApplication : Starting TurmsGatewayApplication v0.10.0-SNAPSHOT using Java 17.0.4.1 with PID 1 (/opt/turms/turms-gateway/BOOT-INF/classes started by root in /opt/turms/turms-gateway)
2023-07-23 07:28:51.672  INFO G ejtkwaus                     main im.turms.gateway.TurmsGatewayApplication : No active profile set, falling back to 1 default profile: "default"
2023-07-23 07:28:52.410  INFO G ejtkwaus                     main      i.t.s.c.i.c.TurmsApplicationContext : The local node with the build properties {version=0.10.0-SNAPSHOT, commitId=39e46efedd7ec88d15ada0f9d0a5edb672c048bc, buildTime=2023-07-23T00:59:27+0000} is running in a production environment
2023-07-23 07:28:52.414  WARN G ejtkwaus                     main      i.t.s.c.i.c.TurmsApplicationContext : The kernel parameter "net.ipv4.tcp_no_metrics_save" is suggested to be "1" but it is "0" actually. You can update it via "sudo sysctl -w net.ipv4.tcp_no_metrics_save=null"
2023-07-23 07:28:52.414  WARN G ejtkwaus                     main      i.t.s.c.i.c.TurmsApplicationContext : The kernel parameter "net.ipv4.tcp_fastopen" is suggested to be "3" but it is "1" actually. You can update it via "sudo sysctl -w net.ipv4.tcp_fastopen=null"
2023-07-23 07:28:52.624  INFO G ejtkwaus                     main             i.t.s.c.i.h.CpuHealthChecker : The CPU has become healthy. The current CPU load is: 0.0
2023-07-23 07:28:52.628  INFO G ejtkwaus                     main                       i.t.s.c.i.c.n.Node : The local node version is: 0.10.0-SNAPSHOT
2023-07-23 07:28:52.682  INFO G ejtkwaus                     main         i.t.s.c.i.c.s.c.ConnectionServer : The local node server started on: 0.0.0.0:7610
2023-07-23 07:28:52.735  INFO G ejtkwaus                     main                org.mongodb.driver.client : MongoClient with metadata {"driver": {"name": "mongo-java-driver|reactive-streams", "version": "4.9.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "aarch64", "version": "5.15.49-linuxkit-pr"}, "platform": "Java/Eclipse Adoptium/17.0.4.1+1"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=null, streamFactoryFactory=NettyStreamFactoryFactory{eventLoopGroup=io.netty.channel.nio.NioEventLoopGroup@34626d4, socketChannelClass=class io.netty.channel.socket.nio.NioSocketChannel, allocator=PooledByteBufAllocator(directByDefault: true), sslContext=null}, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DocumentCodecProvider{}, MapCodecProvider{}, IterableCodecProvider{}, Jsr310CodecProvider{}, BsonCodecProvider{}, im.turms.server.common.storage.mongo.codec.MongoCodecProvider@15ee8861]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[mongodb-router:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[im.turms.server.common.storage.mongo.MongoContext$1@6afaf27]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=UNSPECIFIED, serverApi=null, autoEncryptionSettings=null, contextProvider=null}
2023-07-23 07:28:52.753  INFO G ejtkwaus                     cluster-ClusterId{value='64bcd6b42761552781a692f2', description='null'}-mongodb-router:27017               org.mongodb.driver.cluster : Monitor thread successfully connected to server with description ServerDescription{address=mongodb-router:27017, type=SHARD_ROUTER, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=16157958}
2023-07-23 07:28:52.811  INFO G ejtkwaus                     mongo-event-loop-7-3       i.t.s.c.s.m.o.TurmsMongoOperations : Indexed the collection "leader": {"renewDate": 1}
2023-07-23 07:28:52.813  INFO G ejtkwaus                     mongo-event-loop-7-3       i.t.s.c.s.m.o.TurmsMongoOperations : Indexed the collection "member": {"_id.nodeId": 1}, {"status.lastHeartbeatDate": 1}
2023-07-23 07:28:52.818  INFO G ejtkwaus                     mongo-event-loop-7-3       i.t.s.c.s.m.o.TurmsMongoOperations : Enabled sharding the database: "turms-standalone"
2023-07-23 07:28:52.840  INFO G ejtkwaus                     main    i.t.s.c.i.c.s.c.SharedPropertyService : Fetching shared properties
2023-07-23 07:28:52.887  INFO G ejtkwaus                     mongo-event-loop-7-4    i.t.s.c.i.c.s.c.SharedPropertyService : Fetched shared properties
2023-07-23 07:28:52.897  INFO G ejtkwaus                     main        i.t.s.c.i.c.s.c.ConnectionService : [Client] Connecting to the member: {id=thvqpcoc, host=turms, port=7510}. Retry times: 0
2023-07-23 07:28:52.918  INFO G ejtkwaus                     main   i.t.s.c.i.c.s.d.LocalNodeStatusManager : Registering the local node as a member
2023-07-23 07:28:52.926  INFO G ejtkwaus                     mongo-event-loop-7-1   i.t.s.c.i.c.s.d.LocalNodeStatusManager : Registered the local node as a member
2023-07-23 07:28:53.112  INFO G ejtkwaus                     main                org.mongodb.driver.client : MongoClient with metadata {"driver": {"name": "mongo-java-driver|reactive-streams", "version": "4.9.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "aarch64", "version": "5.15.49-linuxkit-pr"}, "platform": "Java/Eclipse Adoptium/17.0.4.1+1"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=null, streamFactoryFactory=NettyStreamFactoryFactory{eventLoopGroup=io.netty.channel.nio.NioEventLoopGroup@4889fbba, socketChannelClass=class io.netty.channel.socket.nio.NioSocketChannel, allocator=PooledByteBufAllocator(directByDefault: true), sslContext=null}, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DocumentCodecProvider{}, MapCodecProvider{}, IterableCodecProvider{}, Jsr310CodecProvider{}, BsonCodecProvider{}, im.turms.server.common.storage.mongo.codec.MongoCodecProvider@15ee8861]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[mongodb-router:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[im.turms.server.common.storage.mongo.MongoContext$1@6018d82c]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=UNSPECIFIED, serverApi=null, autoEncryptionSettings=null, contextProvider=null}
2023-07-23 07:28:53.114  INFO G ejtkwaus                     cluster-ClusterId{value='64bcd6b52761552781a692f3', description='null'}-mongodb-router:27017               org.mongodb.driver.cluster : Monitor thread successfully connected to server with description ServerDescription{address=mongodb-router:27017, type=SHARD_ROUTER, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=1197500}
2023-07-23 07:28:53.164  INFO G ejtkwaus                     main    i.t.s.c.d.b.m.BlocklistServiceManager : Starting resetting and synchronizing blocked clients
2023-07-23 07:28:53.168  INFO G ejtkwaus                     lettuce-nioEventLoop-16-1    i.t.s.c.d.b.m.BlocklistServiceManager : Reset and synchronized blocked clients
2023-07-23 07:28:53.169  INFO G ejtkwaus                     main    i.t.s.c.d.b.m.BlocklistServiceManager : Starting resetting and synchronizing blocked clients
2023-07-23 07:28:53.170  INFO G ejtkwaus                     lettuce-nioEventLoop-19-1    i.t.s.c.d.b.m.BlocklistServiceManager : Reset and synchronized blocked clients
2023-07-23 07:28:53.180  INFO G ejtkwaus                     main      i.t.g.a.c.t.TcpUserSessionAssembler : TCP server started on: 0.0.0.0:11510
2023-07-23 07:28:53.193  INFO G ejtkwaus                     main  t.g.a.c.w.WebSocketUserSessionAssembler : WebSocket server started on: 0.0.0.0:10510
2023-07-23 07:28:53.196  INFO G ejtkwaus                     main       i.t.s.c.d.a.s.BaseAdminRoleService : Loading all admin roles
2023-07-23 07:28:53.205  INFO G ejtkwaus                     main       i.t.s.c.d.a.s.BaseAdminRoleService : Loaded all admin roles
2023-07-23 07:28:53.208  INFO G ejtkwaus                     main           i.t.s.c.d.a.s.BaseAdminService : Loading all admins
2023-07-23 07:28:53.213  INFO G ejtkwaus                     main           i.t.s.c.d.a.s.BaseAdminService : Loaded all admins
2023-07-23 07:28:53.330  INFO G ejtkwaus                     main im.turms.gateway.TurmsGatewayApplication : Started TurmsGatewayApplication in 1.894 seconds (process running for 2.266)
2023-07-23 07:29:00.977 ERROR G ejtkwaus                     turms-node-connection-client-io-2-2        i.t.s.c.i.c.s.c.ConnectionService : [Client] Failed to connect to member: {id=thvqpcoc, host=turms, port=7510}. Retry times: 0
java.net.UnknownHostException: Failed to resolve 'turms' [A(1)] after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1097)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1044)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:432)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:638)
	at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:489)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:317)
	at io.netty.resolver.dns.DnsQueryContext.finishSuccess(DnsQueryContext.java:309)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1390)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(unknown)

2023-07-23 07:29:10.983  INFO G ejtkwaus                     turms-node-connection-retry        i.t.s.c.i.c.s.c.ConnectionService : [Client] Connecting to the member: {id=thvqpcoc, host=turms, port=7510}. Retry times: 1
2023-07-23 07:29:19.004 ERROR G ejtkwaus                     turms-node-connection-client-io-2-4        i.t.s.c.i.c.s.c.ConnectionService : [Client] Failed to connect to member: {id=thvqpcoc, host=turms, port=7510}. Retry times: 1
java.net.UnknownHostException: Failed to resolve 'turms' [A(1)] after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1097)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1044)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:432)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:638)
	at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:489)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:317)
	at io.netty.resolver.dns.DnsQueryContext.finishSuccess(DnsQueryContext.java:309)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1390)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(unknown)

2023-07-23 07:29:31.786 ERROR G ejtkwaus 1068952036704360873 turms-gateway-tcp-worker-22-1      i.t.g.a.c.c.ClientRequestDispatcher : Failed to handle the service request: SimpleTurmsRequest[requestId=3084446826, type=QUERY_USER_PROFILES_REQUEST, createSessionRequest=null]
im.turms.server.common.infra.cluster.service.rpc.exception.RpcException: 2:1201
2023-07-23 07:29:31.790 ERROR G ejtkwaus 3338928511752048562 turms-gateway-tcp-worker-22-1      i.t.g.a.c.c.ClientRequestDispatcher : Failed to handle the service request: SimpleTurmsRequest[requestId=609584144, type=QUERY_RELATIONSHIPS_REQUEST, createSessionRequest=null]
im.turms.server.common.infra.cluster.service.rpc.exception.RpcException: 2:1201
2023-07-23 07:29:31.802 ERROR G ejtkwaus 1380031758140099086 turms-gateway-tcp-worker-22-1      i.t.g.a.c.c.ClientRequestDispatcher : Failed to handle the service request: SimpleTurmsRequest[requestId=3399842678, type=QUERY_JOINED_GROUP_INFOS_REQUEST, createSessionRequest=null]
im.turms.server.common.infra.cluster.service.rpc.exception.RpcException: 2:1201
2023-07-23 07:29:31.827 ERROR G ejtkwaus  682868072782792313 turms-gateway-tcp-worker-22-1      i.t.g.a.c.c.ClientRequestDispatcher : Failed to handle the service request: SimpleTurmsRequest[requestId=1555415663, type=QUERY_CONVERSATIONS_REQUEST, createSessionRequest=null]
im.turms.server.common.infra.cluster.service.rpc.exception.RpcException: 2:1201
2023-07-23 07:29:31.913 ERROR G ejtkwaus 8369164800596979488 turms-gateway-tcp-worker-22-1      i.t.g.a.c.c.ClientRequestDispatcher : Failed to handle the service request: SimpleTurmsRequest[requestId=4037513149, type=QUERY_FRIEND_REQUESTS_REQUEST, createSessionRequest=null]
im.turms.server.common.infra.cluster.service.rpc.exception.RpcException: 2:1201
2023-07-23 07:29:39.012  INFO G ejtkwaus                     turms-node-connection-retry        i.t.s.c.i.c.s.c.ConnectionService : [Client] Connecting to the member: {id=thvqpcoc, host=turms, port=7510}. Retry times: 2
2023-07-23 07:29:47.022 ERROR G ejtkwaus                     turms-node-connection-client-io-2-5        i.t.s.c.i.c.s.c.ConnectionService : [Client] Failed to connect to member: {id=thvqpcoc, host=turms, port=7510}. Retry times: 2
java.net.UnknownHostException: Failed to resolve 'turms' [A(1)] after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1097)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1044)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:432)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:638)
	at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:489)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:317)
	at io.netty.resolver.dns.DnsQueryContext.finishSuccess(DnsQueryContext.java:309)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1390)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(unknown)


```

**Comment by JamesChenX** [comment]
The logs indicate the turms-gateway server cannot find an A record (IPv4 address) for the hostname `turms`.

From my knowledge, there is no official service named `turms` in turms official docker-compose files this year, we use the service name `turms` for Turms servers years ago. So to figure out why there is no A record for `turms`:
1. You can find out which running Turms server has the `memberHost` that is `turms` in the `member` collection in the MongoDB server.
2. Once you find out the Turms server, you need to check your deployment environment to find out why the turms-gateway server cannot connect to the Turms server that you just found out. Maybe they are deployed in different network environments, and you didn't configure the A record the hostname `turms`, etc.

**Comment by JamesChenX** [comment]
Thanks for reporting.
I have updated the outdated service name, and you can pull the latest code to have a try (You don't need to pull the latest docker images).
