### ISSUE TITLE
gateway 正常关闭执行CLOSE_SESSIONS发生异常

### ISSUE THREAD

**Issue by wangqingchengsg** [turms-im/turms#1286]
打开参数
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful

2023-08-11 02:39:48.713  INFO G glnxhsbx                     turms-shutdown               i.t.g.d.s.s.SessionService : Close the destroy hook...
2023-08-11 02:39:48.715 ERROR G glnxhsbx                     SpringApplicationShutdownHook      i.t.s.c.i.c.TurmsApplicationContext : Caught an error while running the shutdown job: CLOSE_SESSIONS
java.lang.IllegalStateException: Caught an error while clearing local sessions
	at im.turms.gateway.domain.session.service.SessionService.lambda$destroy$1(SessionService.java:190)
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.signal(MonoWhen.java:210)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.signalError(MonoWhen.java:166)
	at reactor.core.publisher.MonoWhen$WhenInner.onError(MonoWhen.java:288)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219)
	at reactor.core.publisher.Operators.error(Operators.java:198)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:48)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:160)
	at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:99)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.Mono.block(Mono.java:1730)
	at im.turms.server.common.infra.context.TurmsApplicationContext.handleContextClosedEvent(TurmsApplicationContext.java:147)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(native)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	at java.lang.Thread.run(Thread.java:833)

caused by: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at im.turms.server.common.access.client.dto.constant.DeviceType.getNumber(DeviceType.java:66)
	at im.turms.server.common.storage.redis.codec.SessionHashFieldCodec.encode(SessionHashFieldCodec.java:35)
	at im.turms.server.common.storage.redis.codec.context.RedisCodecContext.encode(RedisCodecContext.java:101)
	at im.turms.server.common.storage.redis.codec.context.RedisCodecContext.encodeHashField(RedisCodecContext.java:48)
	at im.turms.server.common.storage.redis.codec.context.RedisCodecContext.encodeHashFields(RedisCodecContext.java:55)
	at im.turms.server.common.storage.redis.TurmsRedisClient.lambda$hdel$3(TurmsRedisClient.java:152)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:160)
	at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:99)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.Mono.block(Mono.java:1730)
	at im.turms.server.common.infra.context.TurmsApplicationContext.handleContextClosedEvent(TurmsApplicationContext.java:147)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(native)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	at java.lang.Thread.run(Thread.java:833)

**Comment by wangqingchengsg** [comment]
启动后报错 2100
<img width="963" alt="image" src="https://github.com/turms-im/turms/assets/22829954/cf7a39c8-ce4e-4096-adca-fed1309b20db">

**Comment by wangqingchengsg** [comment]
<img width="1329" alt="image" src="https://github.com/turms-im/turms/assets/22829954/865133f8-422d-457d-8ddd-3b0215e5fe7b">

**Comment by JamesChenX** [comment]
The server has a breaking change to the stored data on Redis months ago, so upgrade all your clients and servers to the latest version, the server will work fine (and you better remove outdated data on Redis).

btw, there are should not breaking changes in the current version v0.10.0 from now on, so if you prefer stability, you can upgrade to the latest version currently and wait for v1.0.0 which will follow the semantic version, and be published in the next few months.
