### ISSUE TITLE
minio plugin error

### ISSUE THREAD

**Issue by Piscen** [turms-im/turms#1378]
docker-compose本地运行一切正常的情况下，加入了minio插件，-Dturms.plugin.network.plugins[0].url=https://github.com/turms-im/turms/releases/download/v0.10.0-SNAPSHOT/turms-plugin-minio-0.10.0-SNAPSHOT.jar，

然后重启就报错了，服务正常启动，不过这个插件没有加载成功，客户端调用storageService报错 6000:The storage feature is enabled but not implemented yet:null:null

我尝试修改了这个配置-Dturms-plugin.minio.mongo.uri=mongodb://localhost:27017/turms，也还是报错，需要有其他的配置么

2024-01-26 16:25:50 2024-01-26 08:25:50.859  INFO S roootknd                     main             i.t.s.c.i.p.PluginRepository : A new plugin with the ID (im.turms.plugin.minio.MinioStoragePlugin) has been registered. The current number of plugins is: 1
2024-01-26 16:25:50 2024-01-26 08:25:50.938  INFO S roootknd                     main             i.t.s.d.g.s.GroupTypeService : Loading all group types
2024-01-26 16:25:50 2024-01-26 08:25:50.951  INFO S roootknd                     main             i.t.s.d.g.s.GroupTypeService : Loaded all group types
2024-01-26 16:25:51 2024-01-26 08:25:51.081  INFO S roootknd                     main   i.t.s.d.u.s.UserPermissionGroupService : Loading all user permission groups and adding the default user permission group
2024-01-26 16:25:51 2024-01-26 08:25:51.092  INFO S roootknd                     main   i.t.s.d.u.s.UserPermissionGroupService : Loaded all user permission groups and added the default user permission group
2024-01-26 16:25:51 2024-01-26 08:25:51.259  INFO S roootknd                     main       i.t.s.c.d.a.s.BaseAdminRoleService : Loading all admin roles
2024-01-26 16:25:51 2024-01-26 08:25:51.266  INFO S roootknd                     main       i.t.s.c.d.a.s.BaseAdminRoleService : Loaded all admin roles
2024-01-26 16:25:51 2024-01-26 08:25:51.271  INFO S roootknd                     main           i.t.s.c.d.a.s.BaseAdminService : Loading all admins
2024-01-26 16:25:51 2024-01-26 08:25:51.364  INFO S roootknd                     main           i.t.s.c.d.a.s.BaseAdminService : Loaded all admins
2024-01-26 16:25:52 2024-01-26 08:25:52.040  INFO S roootknd 5322793383781478669 turms-admin-http-worker-21-1 : |172.19.0.8|f5b9412d-1|2024-01-26 08:25:51.942|getHealthStatus|{}|TRUE|16|
2024-01-26 16:25:52 2024-01-26 08:25:52.254  INFO S roootknd                     main im.turms.service.TurmsServiceApplication : Started TurmsServiceApplication in 9.706 seconds (process running for 10.561)
2024-01-26 16:25:52 2024-01-26 08:25:52.270  INFO S roootknd                     cluster-ClusterId{value='65b36c9028e3d44bddc288c1', description='null'}-localhost:27017               org.mongodb.driver.cluster : Exception in monitor thread while connecting to server localhost:27017
2024-01-26 16:25:52 com.mongodb.MongoSocketOpenException: Exception opening socket
2024-01-26 16:25:52     at com.mongodb.connection.netty.NettyStream$OpenChannelFutureListener.lambda$operationComplete$1(NettyStream.java:529)
2024-01-26 16:25:52     at com.mongodb.internal.Locks.lambda$withLock$0(Locks.java:33)
2024-01-26 16:25:52     at com.mongodb.internal.Locks.checkedWithLock(Locks.java:45)
2024-01-26 16:25:52     at com.mongodb.internal.Locks.withLock(Locks.java:39)
2024-01-26 16:25:52     at com.mongodb.internal.Locks.withLock(Locks.java:32)
2024-01-26 16:25:52     at com.mongodb.connection.netty.NettyStream$OpenChannelFutureListener.operationComplete(NettyStream.java:516)
2024-01-26 16:25:52     at com.mongodb.connection.netty.NettyStream$OpenChannelFutureListener.operationComplete(NettyStream.java:502)
2024-01-26 16:25:52     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
2024-01-26 16:25:52     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
2024-01-26 16:25:52     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
2024-01-26 16:25:52     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
2024-01-26 16:25:52     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
2024-01-26 16:25:52     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
2024-01-26 16:25:52     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
2024-01-26 16:25:52     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
2024-01-26 16:25:52     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
2024-01-26 16:25:52     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
2024-01-26 16:25:52     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2024-01-26 16:25:52     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
2024-01-26 16:25:52     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2024-01-26 16:25:52     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-01-26 16:25:52     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-01-26 16:25:52     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-01-26 16:25:52     at java.lang.Thread.run(unknown)
2024-01-26 16:25:52
2024-01-26 16:25:52 caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
2024-01-26 16:25:52
2024-01-26 16:25:52 caused by: java.net.ConnectException: Connection refused
2024-01-26 16:25:52     at sun.nio.ch.Net.pollConnect(native)
2024-01-26 16:25:52     at sun.nio.ch.Net.pollConnectNow(unknown)
2024-01-26 16:25:52     at sun.nio.ch.SocketChannelImpl.finishConnect(unknown)
2024-01-26 16:25:52     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
2024-01-26 16:25:52     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
2024-01-26 16:25:52     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
2024-01-26 16:25:52     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2024-01-26 16:25:52     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
2024-01-26 16:25:52     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2024-01-26 16:25:52     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-01-26 16:25:52     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-01-26 16:25:52     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-01-26 16:25:52     at java.lang.Thread.run(unknown)

**Comment by Piscen** [comment]
mongo服务没问题，我用python测试是正常的 client = mongo.MongoClient("mongodb://localhost:27017/")

**Comment by JamesChenX** [comment]
From the following logs, your turms servers have a connection problem with `localhost/127.0.0.1:27017`.
It usually happens when you run turms servers in docker-compose with the default network driver (`bridge`), but the MongoDB servers run in the host, so they are isolated in the network, and `localhost/127.0.0.1:27017` won't work for turms servers.
You can simply fix it by updating the network driver of turms servers in docker-compose to `host`, e.g.:
```yaml
turms-service:
  network_mode: host
```


```text
2024-01-26 16:25:52 caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
2024-01-26 16:25:52
2024-01-26 16:25:52 caused by: java.net.ConnectException: Connection refused
```

**Comment by Piscen** [comment]
[log.txt](https://github.com/turms-im/turms/files/14072134/log.txt)
加上network_mode之后连服务都无法启动了

**Comment by Piscen** [comment]
使用默认的配置，依然是Connection refused，docker network inspect turms_im_default 命令运行结果
[
    {
        "Name": "turms_im_default",
        "Id": "9721aae5d29b4e6cab8060fb1b7aac4a2adc953462d1616b6363718c7f9966cd",
        "Created": "2024-01-28T07:19:45.900257066Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.21.0.0/16",
                    "Gateway": "172.21.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "030d9b7e36ab3f954225027a28e71e713c196f6e4828f158bdc2506c3fe55197": {
                "Name": "turms_im-redis-1",
                "EndpointID": "8bd8a76ea40f3f485e13feeead37ed9a91b05dc5364f98c4ce769d5af7b870a9",
                "MacAddress": "02:42:ac:15:00:05",
                "IPv4Address": "172.21.0.5/16",
                "IPv6Address": ""
            },
            "0375b50e9752b06e0060b7fb154b75b890137049b70a8632a9c833c673088a21": {
                "Name": "turms_im-turms-gateway-1",
                "EndpointID": "78c27d6b80861d038532940b12140048382bc5f2d03ebecfb39e11cdb7d224db",
                "MacAddress": "02:42:ac:15:00:07",
                "IPv4Address": "172.21.0.7/16",
                "IPv6Address": ""
            },
            "21f2a839b3f78cf91faaa04348bff1ccac1bea5a6673e9d62d2b7fd5c5af9a1c": {
                "Name": "turms_im-turms-admin-1",
                "EndpointID": "8f0cfe8ce11e3c4437df51e40d8c762efad2553fabb11654c443dd29dd9ae46d",
                "MacAddress": "02:42:ac:15:00:04",
                "IPv4Address": "172.21.0.4/16",
                "IPv6Address": ""
            },
            "32a647d2a77cb95d963fc22e59dcb6ef62102960d89a1a94ea44e35d18a496af": {
                "Name": "turms_im-mongodb-router-1",
                "EndpointID": "d3040e10e8ad681d36a54394af52717ce834705901e2ab4d2a1bebf4ffb6d1f2",
                "MacAddress": "02:42:ac:15:00:06",
                "IPv4Address": "172.21.0.6/16",
                "IPv6Address": ""
            },
            "402033d4e54497ce02338aaae47c1b0d1f1a26f7a1d7c93eb421fdd9a6d02ae0": {
                "Name": "turms_im-mongodb-config-1",
                "EndpointID": "738bf303c4a5781fd5cdbcda446f64cf94e7ff0e3e1d4ff7c454abb916eddb6c",
                "MacAddress": "02:42:ac:15:00:03",
                "IPv4Address": "172.21.0.3/16",
                "IPv6Address": ""
            },
            "5b4373c64167dc648a02adb129f954ebc61d908d6943b402b2e5149e18d06298": {
                "Name": "turms_im-mongodb-shard-1",
                "EndpointID": "90301f5c9db187d9628d483024211e20ea87cd200a4ece6556c3a7104946ba10",
                "MacAddress": "02:42:ac:15:00:02",
                "IPv4Address": "172.21.0.2/16",
                "IPv6Address": ""
            },
            "d61121b645153f7f76112c65909dbdcdcad17570ac46a8d7410704bad68b8d12": {
                "Name": "turms_im-turms-service-1",
                "EndpointID": "62a28bf2d8fc8427942f345e14275c76c8b3ecf9c02c0501998194c90f8fc388",
                "MacAddress": "02:42:ac:15:00:08",
                "IPv4Address": "172.21.0.8/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "turms_im",
            "com.docker.compose.version": "2.19.1"
        }
    }
]

**Comment by Piscen** [comment]
看起来确实是容器间访问有问题，管理后台的插件列表两个接口一直都是超时http://172.18.0.7:9510/plugins，http://172.18.0.8:8510/plugins，我用的最新的docker-compose.standalone.yml文件搭建的，在本地和服务器上都有这个问题，运行环境需要其他的配置么
