### ISSUE TITLE
 the local node has been registered

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1409]
The following exception occurred during restart：

caused by: java.lang.RuntimeException: Failed to bootstrap the local node because the local node has been registered. Local Node: Member(key=Member.Key(clusterId=turms, nodeId=trcpowti), zone=, name=trcpowti, nodeVersion=0.10.0-SNAPSHOT, nodeType=SERVICE, isSeed=false, registrationDate=Mon Mar 04 08:55:44 UTC 2024, isLeaderEligible=true, priority=0, memberHost=turms-service, memberPort=7510, adminApiAddress=http://172.20.0.8:8510, wsAddress=null, tcpAddress=null, udpAddress=null, status=Member.MemberStatus(hasJoinedCluster=false, isHealthy=true, isActive=true, lastHeartbeatDate=Mon Mar 04 08:55:44 UTC 2024)). Registered Node: Member(key=Member.Key(clusterId=turms, nodeId=zhkkldof), zone=, name=zhkkldof, nodeVersion=0.10.0-SNAPSHOT, nodeType=SERVICE, isSeed=false, registrationDate=Mon Mar 04 08:55:12 UTC 2024, isLeaderEligible=true, priority=0, memberHost=turms-service, memberPort=7510, adminApiAddress=http://172.20.0.8:8510, wsAddress=null, tcpAddress=null, udpAddress=null, status=Member.MemberStatus(hasJoinedCluster=true, isHealthy=true, isActive=true, lastHeartbeatDate=Mon Mar 04 08:55:23 UTC 2024))
	at im.turms.server.common.infra.cluster.service.discovery.DiscoveryService.start(DiscoveryService.java:241)
	at im.turms.server.common.infra.cluster.node.Node.start(Node.java:215)
	at im.turms.server.common.infra.cluster.ClusterConfig.node(ClusterConfig.java:60)
	at im.turms.server.common.infra.cluster.ClusterConfig$$SpringCGLIB$$0.CGLIB$node$0(<generated>)
	at im.turms.server.common.infra.cluster.ClusterConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at im.turms.server.common.infra.cluster.ClusterConfig$$SpringCGLIB$$0.node(<generated>)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(unknown)
	at java.lang.reflect.Method.invoke(unknown)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:647)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:639)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:103)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:701)
	at im.turms.server.common.infra.cluster.node.Node$$SpringCGLIB$$0.getSharedProperties(<generated>)
	at im.turms.server.common.infra.property.TurmsPropertiesManager.getGlobalProperties(TurmsPropertiesManager.java:96)
	at im.turms.service.access.admin.throttle.AdminApiRateLimitingManager.<init>(AdminApiRateLimitingManager.java:36)
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(unknown)
	at java.lang.reflect.Constructor.newInstanceWithCaller(unknown)
	at java.lang.reflect.Constructor.newInstance(unknown)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:210)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:111)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:306)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at im.turms.server.common.BaseTurmsApplication.bootstrap(BaseTurmsApplication.java:53)
	at im.turms.service.TurmsServiceApplication.main(TurmsServiceApplication.java:34)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(unknown)
	at java.lang.reflect.Method.invoke(unknown)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)

**Comment by JamesChenX** [comment]
It is designed in this way.

If a Turms server is closed forcibly (e.g. closed by the task manager), it will not have the chance to unregister from the MongoDB (used as a registry service) as it will when closed gracefully (e.g. `kill -9 <pid>`).

In that case, you have to wait 60s for MongoDB to remove the service info of the closed Turms servers from MongoDB automatically.
Otherwise, you will get the error as you mentioned.
