### ISSUE TITLE
镜像插件不加载

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1447]
我按照doc文档描述的，查找不到为什么镜像没有加载插件包的原因。求解答一下，我在本地运行的时候，代码会加载插件的
1.我使用的是最新的镜像，运行的命令是ENV=dev docker compose -f docker-compose.standalone.yml --profile storage up -d，并且在容器的opt/turms/turms-service/plugins下面，有如图所示的jar插件包
![image](https://github.com/turms-im/turms/assets/76037438/97e6dc97-3d6d-4332-8c3e-0646932e9686)

2.启动日志如下：
[描述.txt](https://github.com/turms-im/turms/files/15124954/default.txt)

**Comment by JamesChenX** [comment]
These plugins have been loaded from your logs:

> 2024-04-26 11:11:32 2024-04-26 03:11:32.494  INFO S lmqsczus                     main             i.t.s.c.i.p.PluginRepository : A new plugin with the ID (im.turms.plugin.antispam.AntiSpamPlugin) has been registered. The current number of plugins is: 1
2024-04-26 11:11:32 2024-04-26 03:11:32.496  INFO S lmqsczus                     main             i.t.s.c.i.p.PluginRepository : A new plugin with the ID (im.turms.plugin.rasa.RasaChatbotPlugin) has been registered. The current number of plugins is: 2
2024-04-26 11:11:32 2024-04-26 03:11:32.510  INFO S lmqsczus                     main             i.t.s.c.i.p.PluginRepository : A new plugin with the ID (im.turms.plugin.minio.MinioStoragePlugin) has been registered. The current number of plugins is: 3

If a plugin hasn't loaded, it can only happen when the plugin JAR files aren't in the `plugins` folder at the startup of Turms servers.

**Comment by water2060** [comment]
加载了为什么minio会提示下面的
code: 6000, reason: The storage feature is enabled but not implemented yet
ResponseException(requestId=5834775493295628470, code=6000, reason=The storage feature is enabled but not implemented yet, cause=null)
	at im.turms.client.exception.ResponseException$Companion.from(ResponseException.kt:46)
	at im.turms.client.driver.service.MessageService.didReceiveNotification(MessageService.kt:131)
	at im.turms.client.driver.TurmsDriver.onMessage(TurmsDriver.kt:186)
	at im.turms.client.driver.TurmsDriver.access$onMessage(TurmsDriver.kt:45)
	at im.turms.client.driver.TurmsDriver$connectionService$1$2.invoke(TurmsDriver.kt:61)
	at im.turms.client.driver.TurmsDriver$connectionService$1$2.invoke(TurmsDriver.kt:61)
	at im.turms.client.driver.service.ConnectionService.notifyMessageListeners(ConnectionService.kt:97)
	at im.turms.client.driver.service.ConnectionService.access$notifyMessageListeners(ConnectionService.kt:38)
	at im.turms.client.driver.service.ConnectionService$connect$4$1.invoke(ConnectionService.kt:172)
	at im.turms.client.driver.service.ConnectionService$connect$4$1.invoke(ConnectionService.kt:171)
	at im.turms.client.transport.TcpClient.read(TcpClient.kt:250)
	at im.turms.client.driver.service.ConnectionService$connect$4.invoke(ConnectionService.kt:171)
	at im.turms.client.driver.service.ConnectionService$connect$4.invoke(ConnectionService.kt:160)
	at im.turms.client.transport.TcpClient$startReading$1.invoke(TcpClient.kt:210)
	at im.turms.client.transport.TcpClient$startReading$1.invoke(TcpClient.kt:209)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

1.还有什么要求吗？
2.怎么能像本地一样，看一下加载的详情
这个minio弄了几个月了，还没弄好

**Comment by water2060** [comment]
这是我本地启动的时候，加载的
![image](https://github.com/turms-im/turms/assets/76037438/1f8ab22d-9254-401e-862a-04d551d94c96)

下面是镜像的
![image](https://github.com/turms-im/turms/assets/76037438/327fc510-33eb-425c-a199-ebed184ff5bc)
Started TurmsServiceApplication in 8.351 seconds (process running for 9.774)
2024-04-28 15:39:15 2024-04-28 07:39:15.190  INFO S naohfeyz                     cluster-ClusterId{value='662dfd2331be146d3746c79e', description='null'}-localhost:27017               org.mongodb.driver.cluster : Exception in monitor thread while connecting to server localhost:27017
2024-04-28 15:39:15 com.mongodb.MongoSocketOpenException: Exception opening socket
2024-04-28 15:39:15     at com.mongodb.connection.netty.NettyStream$OpenChannelFutureListener.lambda$operationComplete$1(NettyStream.java:529)
2024-04-28 15:39:15     at com.mongodb.internal.Locks.lambda$withLock$0(Locks.java:33)
2024-04-28 15:39:15     at com.mongodb.internal.Locks.checkedWithLock(Locks.java:45)
2024-04-28 15:39:15     at com.mongodb.internal.Locks.withLock(Locks.java:39)
2024-04-28 15:39:15     at com.mongodb.internal.Locks.withLock(Locks.java:32)
2024-04-28 15:39:15     at com.mongodb.connection.netty.NettyStream$OpenChannelFutureListener.operationComplete(NettyStream.java:516)
2024-04-28 15:39:15     at com.mongodb.connection.netty.NettyStream$OpenChannelFutureListener.operationComplete(NettyStream.java:502)
2024-04-28 15:39:15     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
2024-04-28 15:39:15     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
2024-04-28 15:39:15     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
2024-04-28 15:39:15     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
2024-04-28 15:39:15     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
2024-04-28 15:39:15     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
2024-04-28 15:39:15     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
2024-04-28 15:39:15     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:322)
2024-04-28 15:39:15     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:338)
2024-04-28 15:39:15     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
2024-04-28 15:39:15     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2024-04-28 15:39:15     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
2024-04-28 15:39:15     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2024-04-28 15:39:15     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-04-28 15:39:15     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-04-28 15:39:15     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-04-28 15:39:15     at java.lang.Thread.run(unknown)
2024-04-28 15:39:15 
2024-04-28 15:39:15 caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:27017
2024-04-28 15:39:15 
2024-04-28 15:39:15 caused by: java.net.ConnectException: Connection refused
2024-04-28 15:39:15     at sun.nio.ch.Net.pollConnect(native)
2024-04-28 15:39:15     at sun.nio.ch.Net.pollConnectNow(unknown)
2024-04-28 15:39:15     at sun.nio.ch.SocketChannelImpl.finishConnect(unknown)
2024-04-28 15:39:15     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
2024-04-28 15:39:15     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
2024-04-28 15:39:15     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
2024-04-28 15:39:15     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2024-04-28 15:39:15     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
2024-04-28 15:39:15     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2024-04-28 15:39:15     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-04-28 15:39:15     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-04-28 15:39:15     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-04-28 15:39:15     at java.lang.Thread.run(unknown)
2024-04-28 15:39:15 
2024-04-28 15:39:15 2024-04-28 07:39:15.555  INFO S naohfeyz 1842923241898678417 turms-admin-http-worker-21-1 : |192.168.80.9|207bd0b3-1|2024-04-28 07:39:15.540|getHealthStatus|{}|TRUE|8|
2024-04-28 15:39:22 2024-04-28 07:39:22.627  INFO S naohfeyz                     turms-node-connection-server-worker-5-1        i.t.s.c.i.c.s.c.ConnectionService : [Server] Connected to the member
2024-04-28 15:39:22 2024-04-28 07:39:22.768  WARN S naohfeyz                     turms-node-connection-server-worker-5-1        i.t.s.c.i.c.s.c.ConnectionService : [Server] The connection to an unknown member has been closed unexpectedly
2024-04-28 15:39:22 2024-04-28 07:39:22.769  INFO S naohfeyz                     turms-node-connection-server-worker-5-1        i.t.s.c.i.c.s.c.ConnectionService : [Server] Stop to connect the member because the local node is server
2024-04-28 15:39:23 2024-04-28 07:39:23.438  INFO S naohfeyz                     turms-mongo-change-watcher-1         i.t.s.c.i.c.s.d.DiscoveryService : A new member has been added: Member(key=Member.Key(clusterId=turms, nodeId=egovvuoc), zone=, name=egovvuoc, nodeVersion=0.10.0-SNAPSHOT, nodeType=GATEWAY, isSeed=false, registrationDate=Sun Apr 28 07:39:22 UTC 2024, isLeaderEligible=false, priority=0, memberHost=turms-gateway, memberPort=7610, adminApiAddress=http://192.168.80.10:9510, wsAddress=ws://192.168.80.10:10510, tcpAddress=192.168.80.10:11510, udpAddress=null, status=Member.MemberStatus(hasJoinedCluster=false, isHealthy=true, isActive=true, lastHeartbeatDate=Sun Apr 28 07:39:22 UTC 2024))
2024-04-28 15:39:25 2024-04-28 07:39:25.613  INFO S naohfeyz 8423823909192525767 turms-admin-http-worker-21-2 : |192.168.80.9|6f15392b-1|2024-04-28 07:39:25.612|getHealthStatus|{}|TRUE|1|
2024-04-28 15:39:30 2024-04-28 07:39:30.001  INFO S naohfeyz                     turms-task-manager            i.t.s.d.o.s.StatisticsService : The current online users number is: 0
看不懂是什么原因，这个和minio没有初始化有关系吗？
