### ISSUE TITLE
Not able to load Minio Plugin

### ISSUE THREAD

**Issue by J-artz** [turms-im/turms#1567]
Hi,  I follow the steps given in https://turms-im.github.io/docs/server/development/plugin.html . Start from fresh codebase and change the turms-service and turms-gateway application.yaml profile to dev. 
**When I start my turms-gateway, it throw me this error. This happen when there is a jar file in plugins directory**  
![image](https://github.com/user-attachments/assets/9b394b1e-7175-4d94-a4cd-7b44a0b7984b)

**When I start my turms-service, it throw me this error.** 
![image](https://github.com/user-attachments/assets/2613f09b-ab71-42ba-85d7-90562453e7a3)

I even copy the jar file from turms github assets site , but it still give the same error.  Hopefully someone can shed light on the issue , much appreciated.

**Comment by JamesChenX** [comment]
> When I start my turms-gateway, it throw me this error. This happen when there is a jar file in plugins directory

`turms-minio-plugin` is designed for turms-service should be loaded by turms-service, and that's why turms-gateway throws an exception that it could not find the classes.

> When I start my turms-service, it throw me this error.

The exception will be thrown when Java find corrupted class files, you can download the JAR from `https://github.com/turms-im/turms/releases/download/v0.10.0-SNAPSHOT/turms-plugin-minio-0.10.0-SNAPSHOT.jar` or build it by yourself.

**Comment by J-artz** [comment]
Thanks for your replying. 
> turms-parent/
> ├─ plugins/           <-- This is working for me
>    └─ your-plugin.jar
> ├─ turms-gateway/
> ├─ turms-service/
> 
> turms-parent/
> ├─ turms-gateway/
>    ├─ dist/
>       ├─ plugins/     <-- This is not working for me
>          └─ your-plugin.jar

Can I clarify the correct plugins folder where I should put my plugin jar file at ? 


> The exception will be thrown when Java find corrupted class files, you can download the JAR from https://github.com/turms-im/turms/releases/download/v0.10.0-SNAPSHOT/turms-plugin-minio-0.10.0-SNAPSHOT.jar or build it by yourself.

I have downloaded the exact jar file but it give me the same outcome.

**Comment by duoduoisadog** [comment]
就算下载你提供的turms-plugin-minio也是一样的报错
当name = MinioAsyncClient 时 bytes.length != size
我用了很多总办法尝试修改代码
    public Class<?> findClass(String name) throws ClassNotFoundException {
        String path = name.replace('.', '/').concat(".class");
        ZipEntry entry = zipFile.getEntry(path);
        if (entry == null) {
            throw new ClassNotFoundException("Could not find the class: " + name);
        }
        try (InputStream inputStream = zipFile.getInputStream(entry)) {
            byte[] bytes = inputStream.readAllBytes(); // 确保完整读取数据
            return defineClass(name, bytes, 0, bytes.length);
        } catch (IOException e) {
            throw new InputOutputException("Failed to load class: " + name, e);
        }
    }
    修改后任然报错:
    2024-11-18 06:50:41.705 ERROR S iulskvqb                     main                i.t.s.c.i.p.PluginManager : 
java.lang.RuntimeException: Caught errors while starting plugins
    at im.turms.server.common.infra.plugin.PluginManager.lambda$startPlugins$11(PluginManager.java:672)

    suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
    reactor.core.publisher.Mono.error(Mono.java:299)
    im.turms.server.common.infra.plugin.PluginManager.lambda$startPlugins$11(PluginManager.java:673)
Error has been observed at the following site(s):
    *__________Mono.error ⇢ at im.turms.server.common.infra.plugin.PluginManager.lambda$startPlugins$11(PluginManager.java:673)
    *__Mono.onErrorResume ⇢ at im.turms.server.common.infra.plugin.PluginManager.startPlugins(PluginManager.java:672)
    *_____Mono.thenReturn ⇢ at im.turms.server.common.infra.plugin.PluginManager.startPlugins(PluginManager.java:674)
    |_       Mono.timeout ⇢ at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:200)
Original Stack Trace:
       at im.turms.server.common.infra.plugin.PluginManager.lambda$startPlugins$11(PluginManager.java:672)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
       at reactor.core.publisher.MonoWhen$WhenCoordinator.signal(MonoWhen.java:210)
       at reactor.core.publisher.MonoWhen$WhenInner.onError(MonoWhen.java:412)
       at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
       at reactor.core.publisher.Operators.error(Operators.java:198)
       at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
       at reactor.core.publisher.MonoWhen$WhenCoordinator.signal(MonoWhen.java:210)
       at reactor.core.publisher.MonoWhen$WhenInner.onError(MonoWhen.java:412)
       at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
       at reactor.core.publisher.Operators.error(Operators.java:198)
       at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
       at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:119)
       at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:136)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:294)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:188)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:237)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204)
       at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2869)
       at reactor.core.publisher.SinkOneMulticast.subscribe(SinkOneMulticast.java:98)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265)
       at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
       at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
       at reactor.core.publisher.MonoWhen$WhenCoordinator.request(MonoWhen.java:229)
       at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74)
       at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:101)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
       at reactor.core.publisher.MonoWhen$WhenCoordinator.request(MonoWhen.java:229)
       at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367)
       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74)
       at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:101)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265)
       at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
       at reactor.core.publisher.Mono.subscribeWith(Mono.java:4634)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4534)
       at reactor.core.publisher.Mono.subscribe(Mono.java:4470)
       at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:201)
       at im.turms.server.common.infra.plugin.PluginManager.onApplicationEvent(PluginManager.java:88)
       at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
       at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
       at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
       at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
       at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
       at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:984)
       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627)
       at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
       at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
       at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
       at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
       at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
       at im.turms.server.common.BaseTurmsApplication.bootstrap(BaseTurmsApplication.java:55)
       at im.turms.service.TurmsServiceApplication.main(TurmsServiceApplication.java:37)
       
       
        String region = properties.getRegion();
        String accessKey = properties.getAccessKey();
        String secretKey = properties.getSecretKey();
        MinioAsyncClient.Builder builder = MinioAsyncClient.builder()
                .endpoint(endpoint)
                .credentials(accessKey, secretKey);
    
    builder的时候报错 , 我搞不懂你是怎么能运行的

**Comment by duoduoisadog** [comment]
![gd1](https://github.com/user-attachments/assets/0ab6cd36-37e3-4a91-b771-71297db9588a)
如果不修改任何代码 , 就用你提供的jar,运行就是这个异常,与上面那位一样

**Comment by J-artz** [comment]
@JamesChenX 
Can you kindly relook on the issue? I still stuck on it and other people are having same issue too. Thank you for your time

**Comment by JamesChenX** [comment]
@J-artz Thanks for reporting this bug! The latest docker images and code of turms servers contain the bugfix, and you can pull them currently.

Feel free to reopen this issue if you encounter any related problems.

**Comment by J-artz** [comment]
@JamesChenX  Thank you for your time! I pull the latest code and it seems to be fix. Jia You
