### ISSUE TITLE
admin login error

### ISSUE THREAD

**Issue by duoduoisadog** [turms-im/turms#1572]
2024-11-21 02:42:54.940 ERROR S ljglwsey 2284862864002660480 mongo-event-loop-1-2      i.t.s.c.a.a.w.HttpRequestDispatcher : Caught an error while handling the HTTP request: HEAD{uri=/admins, connection=SimpleConnection{channel=[id: 0xa4344978, L:/127.0.0.1:8510 - R:/127.0.0.1:22821]}}
java.lang.NullPointerException: Cannot invoke "im.turms.server.common.access.admin.permission.RequiredPermission.value()" because "permission" is null
	at im.turms.server.common.access.admin.web.HttpRequestAuthenticator.lambda$authenticate$1(HttpRequestAuthenticator.java:68)

	suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
	reactor.core.publisher.Mono.flatMap(Mono.java:3171)
	im.turms.server.common.access.admin.web.HttpRequestAuthenticator.authenticate(HttpRequestAuthenticator.java:67)
Error has been observed at the following site(s):
	*_________Mono.flatMap ⇢ at im.turms.server.common.access.admin.web.HttpRequestAuthenticator.authenticate(HttpRequestAuthenticator.java:67)
	|_  Mono.switchIfEmpty ⇢ at im.turms.server.common.access.admin.web.HttpRequestAuthenticator.authenticate(HttpRequestAuthenticator.java:78)
	|_ Mono.defaultIfEmpty ⇢ at im.turms.server.common.access.admin.web.HttpRequestDispatcher.lambda$handleRequest$12(HttpRequestDispatcher.java:420)
	|_        Mono.flatMap ⇢ at im.turms.server.common.access.admin.web.HttpRequestDispatcher.lambda$handleRequest$12(HttpRequestDispatcher.java:422)
	*___________Mono.defer ⇢ at im.turms.server.common.access.admin.web.HttpRequestDispatcher.lambda$handleRequest$14(HttpRequestDispatcher.java:401)
	|_      Mono.doFinally ⇢ at im.turms.server.common.access.admin.web.HttpRequestDispatcher.lambda$handleRequest$14(HttpRequestDispatcher.java:430)
	*_________Mono.flatMap ⇢ at im.turms.server.common.access.admin.web.HttpRequestDispatcher.handleRequest(HttpRequestDispatcher.java:401)
	|_       Mono.doOnEach ⇢ at im.turms.server.common.access.admin.web.HttpRequestDispatcher.handle(HttpRequestDispatcher.java:324)
Original Stack Trace:
		at im.turms.server.common.access.admin.web.HttpRequestAuthenticator.lambda$authenticate$1(HttpRequestAuthenticator.java:68)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:880)
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:805)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:163)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$recurseCursor$4(BatchCursorFlux.java:95)
		at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:176)
		at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$1(BatchCursor.java:48)
		at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
		at com.mongodb.internal.operation.AsyncCommandBatchCursor.lambda$next$0(AsyncCommandBatchCursor.java:106)
		at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$2(AsyncCallbackSupplier.java:101)
		at com.mongodb.internal.operation.AsyncCommandBatchCursor$ResourceManager.execute(AsyncCommandBatchCursor.java:238)
		at com.mongodb.internal.operation.AsyncCommandBatchCursor.next(AsyncCommandBatchCursor.java:97)
		at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$2(BatchCursor.java:42)
		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
		at reactor.core.publisher.Mono.subscribeWith(Mono.java:4634)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4534)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4470)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4442)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.recurseCursor(BatchCursorFlux.java:90)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$0(BatchCursorFlux.java:61)
		at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:176)
		at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$33(MongoOperationPublisher.java:524)
		at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:94)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
		at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
		at com.mongodb.internal.async.function.RetryingAsyncCallbackSupplier$RetryingCallback.onResult(RetryingAsyncCallbackSupplier.java:123)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
		at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
		at com.mongodb.internal.async.function.AsyncCallbackSupplier.lambda$whenComplete$1(AsyncCallbackSupplier.java:97)
		at com.mongodb.internal.operation.TurmsFindOperation.lambda$exceptionTransformingCallback$3(TurmsFindOperation.java:133)
		at com.mongodb.internal.operation.AsyncOperationHelper.lambda$transformingReadCallback$20(AsyncOperationHelper.java:441)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
		at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.lambda$executeAsync$0(DefaultServer.java:249)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
		at com.mongodb.internal.connection.CommandProtocolImpl.lambda$executeAsync$0(CommandProtocolImpl.java:88)
		at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.lambda$sendAndReceiveAsync$1(DefaultConnectionPool.java:774)
		at com.mongodb.internal.connection.UsageTrackingInternalConnection.lambda$sendAndReceiveAsync$1(UsageTrackingInternalConnection.java:150)
		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:47)
		at com.mongodb.internal.connection.InternalStreamConnection.lambda$sendCommandMessageAsync$0(InternalStreamConnection.java:532)
		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:826)
		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:789)
		at com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:648)
		at com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:645)
		at com.mongodb.internal.connection.netty.NettyStream.readAsync(NettyStream.java:330)
		at com.mongodb.internal.connection.netty.NettyStream.readAsync(NettyStream.java:274)
		at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:645)
		at com.mongodb.internal.connection.InternalStreamConnection.access$600(InternalStreamConnection.java:93)
		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:779)
		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:763)
		at com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:648)
		at com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:645)
		at com.mongodb.internal.connection.netty.NettyStream.readAsync(NettyStream.java:330)
		at com.mongodb.internal.connection.netty.NettyStream.handleReadResponse(NettyStream.java:357)
		at com.mongodb.internal.connection.netty.NettyStream.access$1100(NettyStream.java:112)
		at com.mongodb.internal.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:433)
		at com.mongodb.internal.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:430)
		at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:1583)

public Mono<Long> authenticate(
            MethodParameterInfo[] params,
            Object[] paramValues,
            HttpHeaders headers,
            @Nullable RequiredPermission permission) {
        Pair<String, String> credentials = parseCredentials(headers);
        if (credentials == null) {
            if (permission == null) {
                return Mono.empty();
            }
            return Mono.error(new HttpResponseException(
                    HttpHandlerResult
                            .unauthorized("Could not find valid credentials from the header: \""
                                    + HttpHeaderNames.AUTHORIZATION
                                    + "\"")));
        }
        return adminService.authenticate(credentials.first(), credentials.second())
                .flatMap(id -> adminService
                        .isAdminAuthorized(params, paramValues, id, permission.value())
                        .flatMap(authorized -> {
                            if (authorized) {
                                return Mono.just(id);
                            }
                            return Mono.error(new HttpResponseException(
                                    HttpHandlerResult
                                            .unauthorized("Unauthorized to access the resource: "
                                                    + permission.value())));
                        }))
                .switchIfEmpty(UNAUTHENTICATED);
    }

把这个代码提出了就好了 , 我不知道这样改对不对,但是能解决我目前的问题
if (permission == null) {
                return Mono.empty();
            }
我很好奇你运行代码不会出现这个问题吗?

**Comment by JamesChenX** [comment]
Thanks for reporting this bug! The latest docker images and code of turms servers contain the bugfix, and you can pull them currently.
