### ISSUE TITLE
Fix "Failed to release a message: PooledUnsafeDirectByteBuf(freed)"

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#430]
2020-07-28 15:16:39.385  WARN 15196 --- [oEventLoop-19-1] io.netty.util.ReferenceCountUtil         : Failed to release a message: PooledUnsafeDirectByteBuf(freed)

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.CompositeByteBuf.addComponents0(CompositeByteBuf.java:404) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.CompositeByteBuf.addComponents(CompositeByteBuf.java:236) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at im.turms.server.common.cluster.service.serialization.SerializationService.serialize(SerializationService.java:57) ~[classes/:na]
	at im.turms.server.common.cluster.service.rpc.RpcService.requestResponse(RpcService.java:114) ~[classes/:na]
	at im.turms.server.common.cluster.service.rpc.RpcService.requestResponse(RpcService.java:99) ~[classes/:na]
	at im.turms.gateway.service.impl.InboundRequestService.sendServiceRequest(InboundRequestService.java:108) ~[classes/:na]
	at im.turms.gateway.service.impl.InboundRequestService.lambda$processServiceRequest$2(InboundRequestService.java:86) ~[classes/:na]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:174) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:355) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.4.0-M1.jar:3.4.0-M1]
	at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onNext(RedisPublisher.java:885) ~[lettuce-core-5.3.1.RELEASE.jar:5.3.1.RELEASE]
	at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:278) ~[lettuce-core-5.3.1.RELEASE.jar:5.3.1.RELEASE]
	at io.lettuce.core.RedisPublisher$SubscriptionCommand.complete(RedisPublisher.java:753) ~[lettuce-core-5.3.1.RELEASE.jar:5.3.1.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:654) ~[lettuce-core-5.3.1.RELEASE.jar:5.3.1.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:614) ~[lettuce-core-5.3.1.RELEASE.jar:5.3.1.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565) ~[lettuce-core-5.3.1.RELEASE.jar:5.3.1.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by JamesChenX** [comment]
We need to track down the lifecycle of the byte buffers hold by RSocket, reactor-netty, and even Spring so that we can know when we need to release the byte buffers by ourselves manually.
They have done the releasing job in the underlying code but not somethings, and it's error-prone.

**Comment by JamesChenX** [comment]
v1.0.0-M1
After debugging, it seems not to be a bug of turms but belongs to reactor-netty or WebFlux and we verified the result by delegating the bytebuf provided by WebFlux (supported by reactor-netty) and set a breakpoint on the release() method, while it's never be called before the refcnt() had become 0 from 1. So the bytebuf should be released by the underlying code unexpectedly. And it's also should not be GCed because we have 8G for the maximum direct memory.

We will dive into the ticket and verify the bug again once the spring boot releases the v2.4.0-RELEASE.

**Comment by JamesChenX** [comment]
Root cause: https://github.com/reactor/reactor-netty/issues/1372.

**Comment by JamesChenX** [comment]
See the reason and the solution for the bug: https://github.com/reactor/reactor-netty/issues/1372
