### ISSUE TITLE
Shutdown turms servers in an orderly, graceful, predictable way

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#962]

**Comment by JamesChenX** [comment]
Turms servers have a lot of components:
1. TCP/UDP/WS server for clients
2. Log processor
3. MongoDB clients
...

We should close these components in a graceful and predictable way so that we don't need to try our luck in shutdown processing.

**Comment by JamesChenX** [comment]
Note that we cannot suppress the change stream exception `java.lang.IllegalStateException: state should be: open` logged by mongo-java-driver because it logs it internally in `com.mongodb.internal.async.ErrorHandlingResultCallback#onResult`, and this should be an enhancement ticket for mongo-java-driver itself:
```java
java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:79)
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:166)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:44)
	at com.mongodb.internal.async.client.ClientSessionBinding.isConnectionSourcePinningRequired(ClientSessionBinding.java:146)
	at com.mongodb.internal.async.client.ClientSessionBinding.getReadConnectionSource(ClientSessionBinding.java:60)
	at com.mongodb.internal.operation.OperationHelper.withAsyncReadConnection(OperationHelper.java:606)
	at com.mongodb.internal.operation.AsyncChangeStreamBatchCursor.retryOperation(AsyncChangeStreamBatchCursor.java:225)
	at com.mongodb.internal.operation.AsyncChangeStreamBatchCursor.access$400(AsyncChangeStreamBatchCursor.java:44)
	at com.mongodb.internal.operation.AsyncChangeStreamBatchCursor$2.onResult(AsyncChangeStreamBatchCursor.java:214)
	at com.mongodb.internal.operation.AsyncChangeStreamBatchCursor$2.onResult(AsyncChangeStreamBatchCursor.java:194)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:407)
	at com.mongodb.internal.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:387)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:276)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:82)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:687)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:159)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:508)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:503)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:767)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:757)
	at com.mongodb.internal.connection.InternalStreamConnection$5.failed(InternalStreamConnection.java:656)
	at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:316)
	at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:347)
	at com.mongodb.connection.netty.NettyStream.access$1100(NettyStream.java:105)
	at com.mongodb.connection.netty.NettyStream$OpenChannelFutureListener$1.operationComplete(NettyStream.java:511)
	at com.mongodb.connection.netty.NettyStream$OpenChannelFutureListener$1.operationComplete(NettyStream.java:508)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1164)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:755)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:772)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:529)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
```
