### ISSUE TITLE
How to query group history messages?

### ISSUE THREAD

**Issue by zhjphp** [turms-im/turms#998]
Application scenarios: 
1. The new user join group, check the history messages.
2. user check offline group message.

I use `js-client: [client.messageService.queryMessages]`
The server response : `1001, NO_CONTENT`, I don't know where is the problem.

And I can't find the configuration noted in the documentation:
[History message]
`
messagePersistent, 
recordsPersistent, 
messageStatusPersistent, 
messageTimeToLiveHours, 
expiredMessagesCheckerCron
`

**Comment by JamesChenX** [comment]
1. `NO_CONTENT` just means there isn't any message for the query filters/conditions. And you can set a breakpoint on the method `im.turms.service.domain.message.access.servicerequest.controller.MessageServiceController#handleQueryMessagesRequest` to debug whether the result `NO_CONTENT` is expected for your case on the server side.

2.  `I can't find the configuration noted in the documentation`, thanks for reminding. They are renamed and I will update the docs later.
And you can check the class for their new names: `im.turms.server.common.infra.property.env.service.business.message.MessageProperties`

**Comment by zhjphp** [comment]
> 1. `NO_CONTENT` just means there isn't any message for the query filters/conditions. And you can set a breakpoint on the method `im.turms.service.domain.message.access.servicerequest.controller.MessageServiceController#handleQueryMessagesRequest` to debug whether the result `NO_CONTENT` is expected for your case on the server side.
> 2. `I can't find the configuration noted in the documentation`, thanks for reminding. They are renamed and I will update the docs later.
>    And you can check the class for their new names: `im.turms.server.common.infra.property.env.service.business.message.MessageProperties`

I not sure if the condition matches the target. I want check the group message, the js-client code like this:
`
client.messageService.queryMessages(
                null,     // [ids]: This parameter refers to the ID of the message, i dont't have the message ids, i only want  check the last 10 message, so i use null.
                true,    // [areGroupMessages]:  The target message is group message.
                false,    // [areSystemMessages]:  is not system messages
                '2801474431517835264',    //  [fromId]:  The string is my "Group Type ID"
            )
`
I want check the last 10 message (I don't care about message sending time) , so i don't use `deliveryDateAfter  deliveryDateBefore` parameter.

The previous code response: `1001, NO_CONTENT`, And i don't think the code has problem, but it's not work.
Please give me some advices。

**Comment by zhjphp** [comment]
I debug `im.turms.service.domain.message.repository#findMessages` ,  and find the problem, `js-client: [client.messageService.queryMessages]` didn't work as I thought, may be a bug.



    client.messageService.queryMessages(

        ids?: string[], 

        areGroupMessages?: boolean,

        areSystemMessages?: boolean,

        fromId?: string,    // There is a problem with this parameter, this parameter corresponds to the "sid" in [mongodb-turms-message], not "tid", that's why I can't find the data.

        deliveryDateAfter?: Date,

        deliveryDateBefore?: Date,

        size = 50

    )

And `im.turms.service.domain.message.access.servicerequest.controller.MessageServiceController#handleQueryMessages` this method does not actually have a parameter corresponding to the "tid" in [mongodb-turms-message]. So it is impossible to find message by group id.  I modified some code: 

    public ClientRequestHandler handleQueryMessagesRequest() {
        .................// 
        return messageService.authAndQueryCompleteMessages(
                            true,
                            idList,
                            areGroupMessages,
                            areSystemMessages,
                            null,    //  This parameter corresponds to the 'sid' in [mongodb-turms-message], it's use clientRequest.userId(), can't get it from client, so i change null.
                            fromId,    //  This parameter corresponds to the 'tid' in [mongodb-turms-message], it's use "userId" befor, i change to "fromId".
                            dateRange,
                            0,
                            size,
                            withTotal)
        .................//
    }

Data can be found after modification.

**Comment by JamesChenX** [comment]
Your solution brings a serious security breach in that everyone can query others' messages.
I have submitted a commit, and you can try it.

**Comment by JamesChenX** [comment]
By the way, I am updating `fromId` to `fromIds` to support query messages from multiple recipients or groups this weekend.
And you can wait for it if it's helpful for your scenarios.

**Comment by zhjphp** [comment]
> Your solution brings a serious security breach in that everyone can query others' messages. I have submitted a commit, and you can try it.

I have tried it, the problem is done, Thank you!
I updated the last commit, but, here is new problem, sometimes client received error( code 500 ), the error has appear on many API, for example `addUser, queryJoinedGroupIds, ...` , the error didn't occur until I updated the commit. 
I can‘t positioning the error, i don't konw what haapend.

java.lang.ClassCastException: 

java.lang.ClassCastException: class im.turms.server.common.storage.mongo.codec.EntityCodec cannot be cast to class im.turms.server.common.storage.mongo.codec.MongoCodec (im.turms.server.common.storage.mongo.codec.EntityCodec and im.turms.server.common.storage.mongo.codec.MongoCodec are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @11dc3715)
	at im.turms.server.common.storage.mongo.codec.MongoCodecProvider.getCodec(MongoCodecProvider.java:48)
	at im.turms.server.common.storage.mongo.codec.MongoCodecProvider.get(MongoCodecProvider.java:44)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:45)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:45)
	at org.bson.internal.OverridableUuidRepresentationCodecRegistry.get(OverridableUuidRepresentationCodecRegistry.java:66)
	at org.bson.internal.OverridableUuidRepresentationCodecRegistry.get(OverridableUuidRepresentationCodecRegistry.java:48)
	at com.mongodb.reactivestreams.client.internal.TurmsFindPublisherImpl.getFindOperation(TurmsFindPublisherImpl.java:232)
	at com.mongodb.reactivestreams.client.internal.TurmsFindPublisherImpl.asAsyncReadOperation(TurmsFindPublisherImpl.java:217)
	at com.mongodb.reactivestreams.client.internal.TurmsFindPublisherImpl.asAsyncReadOperation(TurmsFindPublisherImpl.java:54)
	at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.lambda$batchCursor$3(BatchCursorPublisher.java:125)
	at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.createReadOperationMono(MongoOperationPublisher.java:458)
	at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.createReadOperationMono(MongoOperationPublisher.java:451)
	at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.batchCursor(BatchCursorPublisher.java:129)
	at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.batchCursor(BatchCursorPublisher.java:125)
	at com.mongodb.reactivestreams.client.internal.TurmsFindPublisherImpl.batchCursor(TurmsFindPublisherImpl.java:54)
	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$1(BatchCursorFlux.java:48)
	at reactor.core.publisher.FluxCreate$BaseSink.onRequest(FluxCreate.java:557)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.onRequest(FluxCreate.java:271)
	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$2(BatchCursorFlux.java:44)
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:95)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.subscribe(BatchCursorFlux.java:68)
	at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.subscribe(BatchCursorPublisher.java:121)
	at com.mongodb.reactivestreams.client.internal.TurmsFindPublisherImpl.subscribe(TurmsFindPublisherImpl.java:54)
	at reactor.core.publisher.MonoFromPublisher.subscribe(MonoFromPublisher.java:63)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
	at reactor.core.publisher.Operators.complete(Operators.java:137)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4385)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4515)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4232)
	at im.turms.server.common.infra.cluster.service.rpc.RpcService$1.onRequestReceived(RpcService.java:202)
	at im.turms.server.common.infra.cluster.service.rpc.RpcService$1.onDataReceived(RpcService.java:134)
	at im.turms.server.common.infra.cluster.service.connection.ConnectionService.lambda$onMemberConnectionAdded$14(ConnectionService.java:436)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:364)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at reactor.netty.channel.AbstractChannelMetricsHandler.channelRead(AbstractChannelMetricsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)

**Comment by JamesChenX** [comment]
@zhjphp  BTW, I have updated `fromId` to `fromIds` to support query messages from multiple recipients or groups, you can pull the latest code to try.
The exception seems to have nothing to do with my commit because I just update some logic without modifying any entity or codec, but I will run random tests for all APIs to try to reproduce the this weekend.

**Comment by zhjphp** [comment]
> @zhjphp BTW, I have updated `fromId` to `fromIds` to support query messages from multiple recipients or groups, you can pull the latest code to try. The exception seems to have nothing to do with my commit because I just update some logic without modifying any entity or codec, but I will run random tests for all APIs to try to reproduce the this weekend.

OK, Thank you !!!
